training:
  epochs: 15
  batch_size: 8
  warmup_steps: 4000
  weight_decay: 0.04
  patience: 5
  checkpoint_maestro: /content/drive/MyDrive/Moroccan-IA-music-composer/models/maestro_model.keras
  checkpoint_dir : /content/drive/MyDrive/Moroccan-IA-music-composer/models
  final_model_path: /content/drive/MyDrive/Moroccan-IA-music-composer/models/final_model.keras

data:
  max_seq_len: 2048
  tokens_dir: /content/drive/MyDrive/Moroccan-IA-music-composer/data/processed/tokens

model:
  vocab_size: null      
  embed_dim: 256           # embedding's dimension
  n_heads: 8
  n_layers: 6
  ff_dim: 1024
  dropout: 0.1
 